syntax enable
filetype off
filetype plugin indent on

set list
"set listchars=tab:>.,eol:$
set listchars=tab:╺╴,eol:¬,trail:·,extends:→,precedes:←

set nocompatible
"set autoindent
"set cindent
set number
set ruler
set showcmd
set showmode
set scrolloff=4
set tabstop=4
set shiftwidth=4
set title
set visualbell
set noerrorbells
set mousehide
set mouse=c
set wildmenu
set wildmode=list:longest,full

set hlsearch
set ignorecase
set incsearch
set smartcase

set encoding=utf-8
set laststatus=2
set cmdheight=2
set statusline=%f%m%r%h%w\ [%{&fenc}][%{&ff}\]%y%=%3l,%3c\ [%2p%%]
set background=dark

if &term == "linux"
	colorscheme miro8
else
	set t_Co=256
	colorscheme mirodark
endif

nmap <leader>l :set list!


autocmd! bufreadpost * call LastPosition()
function! LastPosition()
	if line("'\"") && line("'\"")<=line('$')
		normal! `"
	endif
endfunction

au BufWritePost * if getline(1) =~ "^#!.*/bin/"|silent !chmod u+x %|endif


set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle
Bundle 'gmarik/vundle'

"
Bundle 'Lokaltog/vim-powerline'
"Bundle 'zeis/vim-kolor'

if &term =~ '256color'
    " disable Background Color Erase (BCE) so that color schemes
    " render properly when inside 256-color tmux and GNU screen.
    " see also http://sunaku.github.io/vim-256color-bce.html
    set t_ut=
endif

