#!/bin/sh
#


# update X resources db
xrdb -merge $HOME/.Xresources 

# set wallpaper
hsetroot -fill ~/pics/w/Savannah_Lilian_Blot_by_a_Blot_on_the_landscape.jpg

# numlock on
#/usr/bin/numlockx &

# hide mouse cursor
#/usr/bin/unclutter -visible -noevents &

# compositing
#/usr/bin/compton &

# date/time
/usr/bin/dss &

#aplay ~/psone.wav &

# start dwm
exec /usr/bin/dwm 

