#!/bin/sh
#


# update x resources db
xrdb -merge $HOME/.Xresources

# set wallpaper
sh $HOME/.fehbg &

# numlock on
/usr/bin/numlockx &

# hide mouse cursor
/usr/bin/unclutter -visible -noevents &

# compositing
/usr/bin/compton &

# date/time
/usr/local/bin/dss &

# start dwm
exec dwm 

