export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

export LANG="en_RU.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_COLLATE="C"
export LC_ALL=""

export MANWIDTH=110

export EDITOR=vim
export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=r600

zstyle ':completion:*' _complete _ignored _approximate

HISTFILE=~/.histfile
HISTSIZE=8192
SAVEHIST=8192

#setopt APPEND_HISTORY
#setopt CORRECT
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt INC_APPEND_HISTORY

bindkey -e
eval "$(sed -n 's/^/bindkey /; s/: / /p' /etc/inputrc)"
bindkey "^[[A" up-line-or-search
bindkey "^[[B" down-line-or-search

autoload -U compinit
compinit

PROMPT=" %F{blue}:%F{magenta}:%f "
PROMPT2="  %F{blue}:.%f "
RPROMPT="%F{blue}%~%f"

[[ -f ~/.aliases ]] && . ~/.aliases
[[ -f ~/.shfunc ]] && . ~/.shfunc

